import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Triage Companion</h1>

        <p className={styles.description}>Quem é você?</p>

        <div className={styles.grid}>
          <Link href="/doctor">
            <a className={styles.card}>
              <h2>Médico &rarr;</h2>
              <p>Clique aqui para abrir a interface para médicos</p>
            </a>
          </Link>

          <Link href="/triage">
            <a className={styles.card}>
              <h2>Triagem &rarr;</h2>
              <p>Clique aqui para abrir a interface para triagem</p>
            </a>
          </Link>

          <Link href="/pacient">
            <a className={styles.card}>
              <h2>Paciente &rarr;</h2>
              <p>Clique aqui para abrir a interface para pacientes</p>
            </a>
          </Link>

          <Link href="/form">
            <a className={styles.card}>
              <h2>Formulário &rarr;</h2>
              <p>APENAS PARA TESTES - ME DELETE ANTES DE IR PRA PROD</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        Curare 2022 - Todos os direitos reservados
      </footer>
    </div>
  );
}
